# Generated by Django 6.0.4 on 2026-05-07 21:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_remove_profile_first_name_remove_profile_last_name_and_more'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='rank',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.userrank'),
        ),
    ]
