# Generated by Django 6.0.4 on 2026-05-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0005_profile_rank'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('normal', 'Normal'), ('flagged', 'Flagged'), ('suspended', 'Suspended')], default='pending', max_length=20),
        ),
    ]
