# Generated by Django 6.0.4 on 2026-05-08 20:23

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_section_name'),
        ('accounts', '0006_alter_profile_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='admission_trimester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.trimester'),
        ),
        migrations.AddField(
            model_name='profile',
            name='department',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department'),
        ),
        migrations.AddField(
            model_name='profile',
            name='total_xp',
            field=models.IntegerField(default=0),
        ),
    ]
