# Generated by Django 6.0.4 on 2026-05-08 21:28

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_section_name'),
        ('accounts', '0008_alter_profile_student_id'),
        ('media', '0001_initial'),
        ('rankings', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserProfile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_id', models.CharField(blank=True, max_length=10, null=True, unique=True)),
                ('bio', models.TextField(blank=True)),
                ('total_xp', models.IntegerField(default=0)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('normal', 'Normal'), ('flagged', 'Flagged'), ('suspended', 'Suspended')], default='pending', max_length=20)),
                ('is_verified', models.BooleanField(default=False)),
                ('is_graduated', models.BooleanField(default=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('admission_trimester', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.trimester')),
                ('department', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='academics.department')),
                ('profile_picture', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='profile_picture', to='media.photo')),
                ('rank', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='rankings.userrank')),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='profile', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
