# Generated by Django 6.0.4 on 2026-05-12 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_alter_userprofile_student_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='is_moderator',
            field=models.BooleanField(default=False),
        ),
    ]
