# Generated by Django 6.0.4 on 2026-05-06 23:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='section',
            name='name',
            field=models.CharField(max_length=2, unique=True),
        ),
    ]
