# Generated by Django 6.0.4 on 2026-05-07 21:06

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='UserRank',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('max_xp', models.PositiveIntegerField(default=0)),
                ('min_xp', models.PositiveIntegerField(default=0)),
            ],
        ),
    ]
