# Generated by Django 6.0.4 on 2026-05-05 14:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='claim_request_status',
            fields=[
                ('claim_request_status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('claim_request_status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lost_and_found_category',
            fields=[
                ('category_id', models.IntegerField(primary_key=True, serialize=False)),
                ('category_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='lost_and_found_status',
            fields=[
                ('status_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status_name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='claim_request',
            fields=[
                ('claim_id', models.IntegerField(primary_key=True, serialize=False)),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL)),
                ('claim_request_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.claim_request_status')),
            ],
        ),
        migrations.CreateModel(
            name='lost_and_found_post',
            fields=[
                ('post_id', models.IntegerField(primary_key=True, serialize=False)),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lost_or_found_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('lost_and_found_category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.lost_and_found_category')),
                ('photos', models.ManyToManyField(blank=True, related_name='lost_and_found_posts', to='media.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_and_found_posts', to=settings.AUTH_USER_MODEL)),
                ('lost_and_found_status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.lost_and_found_status')),
            ],
        ),
        migrations.CreateModel(
            name='lost_and_found_match',
            fields=[
                ('match_id', models.IntegerField(primary_key=True, serialize=False)),
                ('status', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('claim_id', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lost_found.claim_request')),
                ('found_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_post', to='lost_found.lost_and_found_post')),
                ('lost_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_post', to='lost_found.lost_and_found_post')),
            ],
        ),
        migrations.AddField(
            model_name='claim_request',
            name='lost_and_found_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.lost_and_found_post'),
        ),
    ]
