# Generated by Django 6.0.4 on 2026-05-05 18:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('media', '0001_initial'),
        ('threads', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ClaimRequestStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LostAndFoundCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LostAndFoundMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.CreateModel(
            name='LostAndFoundMatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='LostAndFoundStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ClaimRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='claim_requests', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.claimrequeststatus')),
                ('lost_and_found_match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='lost_found.lostandfoundmatch')),
            ],
        ),
        migrations.CreateModel(
            name='ClaimThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('claim_request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim_thread', to='lost_found.claimrequest')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='threads.thread')),
            ],
        ),
        migrations.AddField(
            model_name='lostandfoundmatch',
            name='status',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.lostandfoundmatchstatus'),
        ),
        migrations.CreateModel(
            name='LostAndFoundPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('lost_or_found_date', models.DateField()),
                ('location', models.CharField(max_length=100)),
                ('type', models.CharField(max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.lostandfoundcategory')),
                ('photos', models.ManyToManyField(blank=True, related_name='lost_and_found_posts', to='media.photo')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_and_found_posts', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.lostandfoundstatus')),
            ],
        ),
        migrations.AddField(
            model_name='lostandfoundmatch',
            name='found_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='found_post', to='lost_found.lostandfoundpost'),
        ),
        migrations.AddField(
            model_name='lostandfoundmatch',
            name='lost_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_post', to='lost_found.lostandfoundpost'),
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='found_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='lost_found.lostandfoundpost'),
        ),
    ]
