# Generated by Django 6.0.4 on 2026-05-06 12:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0001_initial'),
        ('media', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostandfoundpost',
            name='photos',
        ),
        migrations.AlterField(
            model_name='lostandfoundpost',
            name='type',
            field=models.CharField(max_length=20),
        ),
        migrations.CreateModel(
            name='LostAndFoundPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('caption', models.CharField(blank=True, max_length=255)),
                ('attached_at', models.DateTimeField(auto_now_add=True)),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lost_found_attachments', to='media.photo')),
                ('post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='post_photos', to='lost_found.lostandfoundpost')),
            ],
        ),
    ]
