# Generated by Django 6.0.4 on 2026-05-06 12:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0002_remove_lostandfoundpost_photos_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfoundpost',
            name='type',
            field=models.CharField(choices=[('lost', 'Lost'), ('found', 'Found')], max_length=20),
        ),
    ]
