# Generated by Django 6.0.4 on 2026-05-06 12:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0003_alter_lostandfoundpost_type'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lostandfoundphoto',
            name='attached_at',
        ),
        migrations.RemoveField(
            model_name='lostandfoundphoto',
            name='caption',
        ),
    ]
