# Generated by Django 6.0.4 on 2026-05-08 01:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0004_remove_lostandfoundphoto_attached_at_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LostAndFoundTag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.AlterField(
            model_name='lostandfoundpost',
            name='type',
            field=models.CharField(choices=[('LOST', 'Lost'), ('FOUND', 'Found')], max_length=20),
        ),
        migrations.AddField(
            model_name='lostandfoundpost',
            name='tags',
            field=models.ManyToManyField(blank=True, to='lost_found.lostandfoundtag'),
        ),
    ]
