# Generated by Django 6.0.4 on 2026-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0005_lostandfoundtag_alter_lostandfoundpost_type_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='claimrequest',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostandfoundmatch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='lostandfoundpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ClaimRequestStatus',
        ),
        migrations.DeleteModel(
            name='LostAndFoundMatchStatus',
        ),
        migrations.DeleteModel(
            name='LostAndFoundStatus',
        ),
    ]
