# Generated by Django 6.0.4 on 2026-05-09 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0007_alter_lostandfoundpost_type'),
        ('threads', '0007_alter_messagevote_vote_type_alter_thread_visibility_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='lostandfoundphoto',
            options={'ordering': ['order']},
        ),
        migrations.RenameField(
            model_name='claimrequest',
            old_name='user',
            new_name='claimer',
        ),
        migrations.AlterUniqueTogether(
            name='claimrequest',
            unique_together={('claimer', 'found_post')},
        ),
        migrations.AddField(
            model_name='claimrequest',
            name='lost_post',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='outgoing_claims', to='lost_found.lostandfoundpost'),
        ),
        migrations.AlterField(
            model_name='claimrequest',
            name='found_post',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='received_claims', to='lost_found.lostandfoundpost'),
        ),
        migrations.AlterField(
            model_name='claimthread',
            name='thread',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='claim_thread', to='threads.thread'),
        ),
        migrations.AlterField(
            model_name='lostandfoundtag',
            name='name',
            field=models.CharField(max_length=50, unique=True),
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='deleted_at',
        ),
        migrations.RemoveField(
            model_name='claimrequest',
            name='lost_and_found_match',
        ),
        migrations.CreateModel(
            name='SuggestedMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('score', models.PositiveIntegerField(default=0, help_text='Tag-overlap count used to rank suggestions.')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('DISMISSED', 'Dismissed'), ('CONVERTED', 'Converted')], default='PENDING', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('found_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_as_found', to='lost_found.lostandfoundpost')),
                ('lost_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggested_as_lost', to='lost_found.lostandfoundpost')),
            ],
            options={
                'ordering': ['-score', '-created_at'],
                'unique_together': {('lost_post', 'found_post')},
            },
        ),
        migrations.DeleteModel(
            name='LostAndFoundMatch',
        ),
    ]
