# Generated by Django 6.0.4 on 2026-05-10 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0008_alter_lostandfoundphoto_options_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfoundpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
