# Generated by Django 6.0.4 on 2026-05-10 17:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lost_found', '0009_alter_lostandfoundpost_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lostandfoundpost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('rejected', 'Rejected'), ('resolved', 'Resolved')], default='pending', max_length=20),
        ),
    ]
