# Generated by Django 6.0.4 on 2026-05-07 17:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('threads', '0005_alter_threadparticipant_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ExchangeMatchStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangePostStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeSessionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='MatchDecisionStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='SessionFeedbackStatus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='Skill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill_name', models.CharField(max_length=100)),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='ExchangePost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('users_post', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_posts', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_exchange.exchangepoststatus')),
                ('skills_offered', models.ManyToManyField(related_name='offered_in_posts', to='skill_exchange.skill')),
                ('skills_requested', models.ManyToManyField(related_name='requested_in_posts', to='skill_exchange.skill')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeMatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('matched_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_exchange.exchangematchstatus')),
                ('ex_p_a', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_post_a', to='skill_exchange.exchangepost')),
                ('ex_p_b', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='exchange_post_b', to='skill_exchange.exchangepost')),
            ],
        ),
        migrations.CreateModel(
            name='ExchangeSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('match', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='skill_exchange.exchangematch')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='threads.thread')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_exchange.exchangesessionstatus')),
            ],
        ),
        migrations.CreateModel(
            name='MatchDecision',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('decided_at', models.DateTimeField(auto_now_add=True)),
                ('decided_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='match_decisions', to=settings.AUTH_USER_MODEL)),
                ('exchange_match', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_exchange.exchangematch')),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_exchange.matchdecisionstatus')),
            ],
        ),
        migrations.CreateModel(
            name='SessionFeedback',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rating', models.DecimalField(decimal_places=2, max_digits=3)),
                ('comment', models.TextField(blank=True, null=True)),
                ('given_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('exchange_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_exchange.exchangesession')),
                ('rated_user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_received', to=settings.AUTH_USER_MODEL)),
                ('rater', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedback_given', to=settings.AUTH_USER_MODEL)),
                ('status', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_exchange.sessionfeedbackstatus')),
            ],
        ),
    ]
