# Generated by Django 6.0.4 on 2026-05-10 09:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='skill_exchange.skill')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_skills', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.DeleteModel(
            name='ExchangeMatchStatus',
        ),
        migrations.DeleteModel(
            name='ExchangePostStatus',
        ),
        migrations.DeleteModel(
            name='ExchangeSessionStatus',
        ),
        migrations.DeleteModel(
            name='MatchDecisionStatus',
        ),
        migrations.DeleteModel(
            name='SessionFeedbackStatus',
        ),
    ]
