# Generated by Django 6.0.4 on 2026-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangematch',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('closed', 'Closed')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangepost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='exchangesession',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('active', 'Active'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='matchdecision',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('accepted', 'Accepted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.AlterField(
            model_name='sessionfeedback',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('submitted', 'Submitted'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
        migrations.DeleteModel(
            name='ExchangeMatchStatus',
        ),
        migrations.DeleteModel(
            name='ExchangePostStatus',
        ),
        migrations.DeleteModel(
            name='ExchangeSessionStatus',
        ),
        migrations.DeleteModel(
            name='MatchDecisionStatus',
        ),
        migrations.DeleteModel(
            name='SessionFeedbackStatus',
        ),
    ]
