# Generated by Django 6.0.4 on 2026-05-10 20:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0002_alter_exchangematch_status_alter_exchangepost_status_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='exchangematch',
            unique_together={('ex_p_a', 'ex_p_b')},
        ),
    ]
