# Generated by Django 6.0.4 on 2026-05-08 20:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0003_rename_skills_requested_exchangepost_skills_needed_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exchangepost',
            old_name='users_post',
            new_name='author',
        ),
        migrations.AlterField(
            model_name='exchangepost',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
