# Generated by Django 6.0.4 on 2026-05-11 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0003_alter_exchangematch_unique_together'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exchangepost',
            name='status',
            field=models.CharField(choices=[('pending', 'Pending'), ('matched', 'Matched'), ('rejected', 'Rejected')], default='pending', max_length=20),
        ),
    ]
