# Generated by Django 6.0.4 on 2026-05-12 18:50

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('skill_exchange', '0004_alter_exchangepost_status'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SessionEndRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('approved', 'Approved'), ('denied', 'Denied')], default='pending', max_length=20)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('responded_at', models.DateTimeField(blank=True, null=True)),
                ('exchange_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='end_requests', to='skill_exchange.exchangesession')),
                ('requested_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='session_end_requests_made', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'unique_together': {('exchange_session', 'status')},
            },
        ),
    ]
