# Generated by Django 6.0.4 on 2026-05-06 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0002_messageattachment_order'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagevote',
            name='vote_type',
            field=models.CharField(choices=[('UPVOTE', 'Upvote'), ('DOWNVOTE', 'Downvote')], max_length=10),
        ),
        migrations.AlterField(
            model_name='thread',
            name='visibility',
            field=models.CharField(choices=[('PUBLIC', 'Public'), ('PRIVATE', 'Private')], default='PUBLIC', max_length=20),
        ),
    ]
