# Generated by Django 6.0.4 on 2026-05-06 22:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0003_alter_messagevote_vote_type_alter_thread_visibility'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='thread',
            name='created_by',
        ),
    ]
