# Generated by Django 6.0.4 on 2026-05-06 22:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0004_remove_thread_created_by'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadparticipant',
            name='role',
            field=models.CharField(choices=[('AUTHOR', 'Author'), ('MEMBER', 'Member'), ('MODERATOR', 'Moderator')], default='MEMBER', max_length=50),
        ),
    ]
