# Generated by Django 6.0.4 on 2026-05-08 11:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("threads", "0005_alter_threadparticipant_role"),
    ]

    operations = [
        migrations.AlterField(
            model_name="threadmessage",
            name="status",
            field=models.CharField(
                choices=[("sent", "Sent"), ("deleted", "Deleted")],
                default="sent",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="thread",
            name="status",
            field=models.CharField(
                choices=[
                    ("open", "Open"),
                    ("closed", "Closed"),
                    ("archived", "Archived"),
                ],
                default="open",
                max_length=20,
            ),
        ),
        migrations.AlterField(
            model_name="messagevote",
            name="status",
            field=models.CharField(
                choices=[("active", "Active"), ("revoked", "Revoked")],
                default="active",
                max_length=20,
            ),
        ),
        migrations.DeleteModel(
            name="ThreadMessageStatus",
        ),
        migrations.DeleteModel(
            name="ThreadStatus",
        ),
        migrations.DeleteModel(
            name="VoteStatus",
        ),
    ]
