# Generated by Django 6.0.4 on 2026-05-08 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0006_alter_threadmessage_status_alter_thread_status_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='messagevote',
            name='vote_type',
            field=models.CharField(choices=[('upvote', 'Upvote'), ('downvote', 'Downvote')], max_length=10),
        ),
        migrations.AlterField(
            model_name='thread',
            name='visibility',
            field=models.CharField(choices=[('public', 'Public'), ('private', 'Private')], default='PUBLIC', max_length=20),
        ),
        migrations.AlterField(
            model_name='threadparticipant',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('member', 'Member'), ('moderator', 'Moderator')], default='MEMBER', max_length=50),
        ),
    ]
