# Generated by Django 6.0.4 on 2026-05-11 00:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0007_alter_messagevote_vote_type_alter_thread_visibility_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='threadparticipant',
            name='role',
            field=models.CharField(choices=[('author', 'Author'), ('member', 'Member'), ('moderator', 'Moderator')], default='member', max_length=50),
        ),
    ]
