# Generated by Django 6.0.4 on 2026-05-11 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('threads', '0008_alter_threadparticipant_role'),
    ]

    operations = [
        migrations.AddField(
            model_name='threadmessage',
            name='is_pinned',
            field=models.BooleanField(default=False),
        ),
    ]
