# Generated by Django 6.0.4 on 2026-05-07 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('academics', '0002_alter_section_name'),
        ('threads', '0005_alter_threadparticipant_role'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ForumThread',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_announcement', models.BooleanField(default=False)),
                ('is_pinned', models.BooleanField(default=False)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to=settings.AUTH_USER_MODEL)),
                ('course', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='academics.course')),
                ('department', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='academics.department')),
                ('section', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='academics.section')),
                ('thread', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='threads.thread')),
                ('trimester', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='academics.trimester')),
            ],
        ),
    ]
