# Generated by Django 6.0.4 on 2026-05-11 16:34

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('academics', '0002_alter_section_name'),
        ('forum', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='forumthread',
            name='section',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to='academics.section'),
        ),
        migrations.AlterField(
            model_name='forumthread',
            name='trimester',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='forum_threads', to='academics.trimester'),
        ),
    ]
