# Generated by Django 6.0.4 on 2026-05-12 13:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('forum', '0002_alter_forumthread_section_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='forumthread',
            name='section',
        ),
    ]
